# Site settings
title: WebConfs - A blog about web conferences
email: coolwebconfs@gmail.com
description: A blog about my favorite web conferences.
url: "http://webconfs.me" # the base hostname & protocol for your site
twitter_username: test
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title


#    Default settings

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      category: blogging 
      author: Cool Dude
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
